apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resolver
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resolver
            image: readytalk/dns-geo-analyzer
            imagePullPolicy: Always
          restartPolicy: OnFailure
