apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resolver
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resolver
            image: readytalk/dns-geo-analyzer:latest
            imagePullPolicy: Always
            env:
            - name: NAMERSERVERS
              value: "google,8.8.8.8 cloudflare,1.1.1.1"
            - name: SITES
              value: "google,google.com"
          restartPolicy: OnFailure
